#!/bin/bash
# Copyright 2020 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

cp _userconfig.yml.example _userconfig.yml

sed -i "s#%GA_TOKEN%#$GOOGLE_ANALYTICS#g" _userconfig.yml
sed -i "s#%GPSE_ID%#$GOOGLE_PSE#g" _userconfig.yml

docker build \
    --build-arg jekyll_env=production \
    -t splintercommunity/splinter-docs \
    -f ci/website.dockerfile \
    .

docker push splintercommunity/splinter-docs
