name: Publish Docker Image

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  publish_docker_main:
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish images to dockerhub
        run: ./ci/publish-docker
        env:
          CARGO_TERM_COLOR: always

